// AUTO-GENERATED by scripts/render-renewal-videos.ts — do not edit by hand.
// Maps each warm combo slug (consulate-caseType-booklet) to its pre-rendered
// 9:16 MP4 on S3. Empty entries fall back to the live in-browser <Player>.
export interface RenewalVideoMeta {
  slug: string
  mp4: string
  poster: string
  duration: string // ISO 8601
  durationLabel: string
  uploadDate: string
  width: number
  height: number
}

export const RENEWAL_VIDEOS: Record<string, RenewalVideoMeta> = {
  "new-york-normal-36": {
    "slug": "new-york-normal-36",
    "mp4": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-jguuxrk7ia/renders/yk2gy6ro11/out.mp4",
    "poster": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-jguuxrk7ia/renders/fy4dera7ir/out.png",
    "duration": "PT18S",
    "durationLabel": "0:18",
    "uploadDate": "2026-07-12",
    "width": 1080,
    "height": 1920
  },
  "new-york-normal-60": {
    "slug": "new-york-normal-60",
    "mp4": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-jguuxrk7ia/renders/jmvvgglx7s/out.mp4",
    "poster": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-jguuxrk7ia/renders/r82ddi65s5/out.png",
    "duration": "PT18S",
    "durationLabel": "0:18",
    "uploadDate": "2026-07-12",
    "width": 1080,
    "height": 1920
  }
}
